FROM  nvidia/cuda:10.2-devel

RUN apt-get update && apt-get install -y python3.7 python3.7-dev python3.7-distutils python3-pip curl git bash nano mlocate

# Set default Python version
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
RUN update-alternatives --set python3 /usr/bin/python3.7

WORKDIR /opt/service
COPY requirements.txt .

RUN pip3 install --upgrade pip && \
    pip3 install -r requirements.txt

COPY . .

RUN apt-get install -y libcudnn7 libcudnn7-dev

ENV LC_ALL=C.UTF-8 \
    LANG=C.UTF-8 \
    PYTHONDONTWRITEBYTECODE=1 \
    LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/lib/x86_64-linux-gnu/

RUN ln -s /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudart.so.10.2 /usr/lib/x86_64-linux-gnu/libcudart.so.10.0 && \
    ln -s /usr/lib/x86_64-linux-gnu/libcublas.so.10 /usr/lib/x86_64-linux-gnu/libcublas.so.10.0 && \
    ln -s /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcufft.so.10 /usr/lib/x86_64-linux-gnu/libcufft.so.10.0 && \
    ln -s /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcurand.so.10 /usr/lib/x86_64-linux-gnu/libcurand.so.10.0 && \
    ln -s /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcusolver.so.10 /usr/lib/x86_64-linux-gnu/libcusolver.so.10.0 && \
    ln -s /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcusparse.so.10 /usr/lib/x86_64-linux-gnu/libcusparse.so.10.0

CMD ["/bin/bash"]
